pools:
  standard: titangrch37standard
  highmem: titangrch37highmem
  multicore: titangrch37multicore

memory:
  low: 2
  med: 4
  high: 15

max_cores: null

reference_genome: /refdata/GRCh37-lite.fa

# Chromosomes for copy number analysis
chromosomes: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y']

# Museq parameters
museq_params:
  mutationseq: /usr/local/museq/

  mutationseq_model: /refdata/model_single_v4.0.2_anaconda_sk_0.13.1.npz

# Convert museq parameters
convert_museq_vcf2counts_params:
  positions_file: /refdata/common_all_dbSNP138.pos

# Read counter parameters
readcounter_params:
  w: 1000
  q: 0

# Wig file correction parameters
calc_correctreads_wig_params:
  gc: /refdata/GRCh37-lite.gc.ws_1000.wig

# Titan parameters
titan_params:
  num_clusters: 1
  ploidy: 2
  y_threshold: 20

# Pygene parameters
pygene_params:
  gene_sets_gtf: /refdata/Homo_sapiens.GRCh37.73.gtf

map: /refdata/GRCh37-lite.map.ws_1000.wig
genome_type: NCBI